FROM mcr.microsoft.com/dotnet/core/sdk:8.0 AS build
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore


COPY . ./
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:8.0
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet","WebAPI1807.dll"]